### ISSUE TITLE
Right shift with cursor on leftmost position causes crash

### ISSUE THREAD

**Issue by Babbiorsetto** [matheusvalbert/programmer-calculator-android#1]
App version: 1.2.3

Repro:
1. Open app
2. Switch to binary
3. Type in something
4. Place the cursor on the far left
5. Tap right shift
6. App crashes

I think this is setting the cursor position to a negative value
https://github.com/matheusvalbert/programmer-calculator-android/blob/21f152d379a5e323418d8717fb5bcc469b38619f/app/src/main/java/com/matheusvalbert/programmercalculator/core/usecase/ShiftRightUseCase.kt#L14-L17
Nice app by the way, keep it up.

**Comment by matheusvalbert** [comment]
Thanks for reporting the bug, I fixed the problem and uploaded a new version (1.2.4) on Play Store (which will be available soon).
If you find any new bugs or have any feature suggestions, please let me know.

Regards.
